"""atualizacao da col img para img_not

Revision ID: 0138253e9134
Revises: 38b11a852f2b
Create Date: 2021-11-08 13:24:49.127748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0138253e9134'
down_revision = '38b11a852f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_not', sa.String(length=100), nullable=True))
        batch_op.drop_column('img')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('img_not')

    # ### end Alembic commands ###
