"""atualizacao na tabela de noticia add datahora

Revision ID: 1408dcc63ce4
Revises: 540950a902e3
Create Date: 2021-12-03 11:26:08.037397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1408dcc63ce4'
down_revision = '540950a902e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datahora', sa.DateTime(), nullable=False))
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data', mysql.VARCHAR(length=15), nullable=False))
        batch_op.drop_column('datahora')

    # ### end Alembic commands ###
