"""novas tabelas Campanha e Noticia

Revision ID: 186ef0862db3
Revises: f72e041a460a
Create Date: 2021-11-05 11:27:09.656723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186ef0862db3'
down_revision = 'f72e041a460a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_capa', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membro', schema=None) as batch_op:
        batch_op.drop_column('img_capa')

    # ### end Alembic commands ###
