"""Tabela Categoria

Revision ID: 28c099a8784c
Revises: ceb81cd11f40
Create Date: 2021-12-07 11:26:45.354260

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28c099a8784c'
down_revision = 'ceb81cd11f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categoria')),
    sa.UniqueConstraint('categoria', name=op.f('uq_categoria_categoria'))
    )
    op.create_table('noticiatag',
    sa.Column('noticia_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['noticia_id'], ['noticia.id'], name=op.f('fk_noticiatag_noticia_id_noticia')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_noticiatag_tag_id_tag')),
    sa.PrimaryKeyConstraint('noticia_id', 'tag_id', name=op.f('pk_noticiatag'))
    )
    op.drop_table('noticatag')
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_noticia_categoria_id_categoria'), 'categoria', ['categoria_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_noticia_categoria_id_categoria'), type_='foreignkey')
        batch_op.drop_column('categoria_id')

    op.create_table('noticatag',
    sa.Column('noticia_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tag_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['noticia_id'], ['noticia.id'], name='fk_noticatag_noticia_id_noticia'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='fk_noticatag_tag_id_tag'),
    sa.PrimaryKeyConstraint('noticia_id', 'tag_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('noticiatag')
    op.drop_table('categoria')
    # ### end Alembic commands ###
