"""atualizaçao da tabela noticia

Revision ID: 38b11a852f2b
Revises: fee5d5b82417
Create Date: 2021-11-08 13:23:16.914600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38b11a852f2b'
down_revision = 'fee5d5b82417'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.String(length=100), nullable=True))
        batch_op.drop_column('img_not')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_not', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('img')

    # ### end Alembic commands ###
