"""felipe testando algo

Revision ID: 4518d798854a
Revises: 0138253e9134
Create Date: 2021-11-11 18:18:10.564356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4518d798854a'
down_revision = '0138253e9134'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('membro_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_noticia_membro_id_membro'), 'membro', ['membro_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_noticia_membro_id_membro'), type_='foreignkey')
        batch_op.drop_column('membro_id')

    # ### end Alembic commands ###
