"""atualizar teste

Revision ID: 6465433f0e59
Revises: f2202f87b0bb
Create Date: 2021-11-19 13:28:49.237096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6465433f0e59'
down_revision = 'f2202f87b0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil', sa.String(length=100), nullable=True))
        batch_op.drop_column('img_perfil')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_perfil', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('perfil')

    # ### end Alembic commands ###
