"""aumentando o numero de caracteres da descricao

Revision ID: 74b5c6438796
Revises: af8b555c4614
Create Date: 2021-12-15 22:13:07.347365

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '74b5c6438796'
down_revision = 'af8b555c4614'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.String(length=5000), nullable=False))
        batch_op.drop_column('descricaoo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricaoo', mysql.VARCHAR(length=5000), nullable=False))
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###
