"""tornando o email unique

Revision ID: 8e0e19569864
Revises: f2d8361595b5
Create Date: 2021-10-27 21:15:30.144099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0e19569864'
down_revision = 'f2d8361595b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membro', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_membro_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membro', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_membro_email'), type_='unique')

    # ### end Alembic commands ###
