"""atualização da tabela de noticias

Revision ID: af8b555c4614
Revises: 24daba43c6f1
Create Date: 2021-12-15 22:11:46.268875

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af8b555c4614'
down_revision = '24daba43c6f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricaoo', sa.String(length=5000), nullable=False))
        batch_op.drop_column('descricao')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', mysql.VARCHAR(length=300), nullable=False))
        batch_op.drop_column('descricaoo')

    # ### end Alembic commands ###
