"""resolvendo bug na tabela noticia coluna img_not

Revision ID: b2bfb0b97f34
Revises: 99e51675544a
Create Date: 2021-12-07 15:42:04.962245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2bfb0b97f34'
down_revision = '99e51675544a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_not', sa.String(length=100), nullable=True))
        batch_op.drop_column('img_noot')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('noticia', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img_noot', mysql.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('img_not')

    # ### end Alembic commands ###
