"""Tabela Tag

Revision ID: ceb81cd11f40
Revises: 1408dcc63ce4
Create Date: 2021-12-05 18:35:51.011781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceb81cd11f40'
down_revision = '1408dcc63ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag')),
    sa.UniqueConstraint('tag', name=op.f('uq_tag_tag'))
    )
    op.create_table('noticatag',
    sa.Column('noticia_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['noticia_id'], ['noticia.id'], name=op.f('fk_noticatag_noticia_id_noticia')),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_noticatag_tag_id_tag')),
    sa.PrimaryKeyConstraint('noticia_id', 'tag_id', name=op.f('pk_noticatag'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noticatag')
    op.drop_table('tag')
    # ### end Alembic commands ###
