"""ajuste 4 - Felipe

Revision ID: f2d8361595b5
Revises: f7b36cd4c4e8
Create Date: 2021-10-22 17:53:32.983546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f2d8361595b5'
down_revision = 'f7b36cd4c4e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=20), nullable=False))
        batch_op.drop_column('membro_telefone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('membro', schema=None) as batch_op:
        batch_op.add_column(sa.Column('membro_telefone', mysql.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
