"""novas tabelas Campanha e Noticia

Revision ID: fee5d5b82417
Revises: 186ef0862db3
Create Date: 2021-11-05 12:06:52.296954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fee5d5b82417'
down_revision = '186ef0862db3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campanha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('img_cam', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campanha'))
    )
    op.create_table('noticia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('autor', sa.String(length=100), nullable=False),
    sa.Column('data', sa.String(length=15), nullable=False),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('img_not', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_noticia'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noticia')
    op.drop_table('campanha')
    # ### end Alembic commands ###
